using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class PlayerUI : MonoBehaviour
{
    const float iconSlideIntensity = 0.3f;

    [SerializeField]
    Vector2 currentCharaIconPos;
    [SerializeField]
    float currentCharaIconSize;
    [SerializeField]
    float subCharaIconSize;
    [SerializeField]
    float tabSize;
    [SerializeField]
    float imgEXRate;

    [SerializeField]
    Canvas playPartCanvas;
    [SerializeField]
    Image[] charaImages;
    [SerializeField]
    Image[] charaImageTrays;
    [SerializeField]
    Image emptyImage;
    [SerializeField]
    Image reviveImage;
    [SerializeField]
    TMP_Text reviveCount;
    [SerializeField]
    Canvas gameOverCanvas;
    [SerializeField]
    Canvas goalCanvas;
    [SerializeField]
    TMP_Text resultKillCount;
    [SerializeField]
    TMP_Text resultReviveCount;
    [SerializeField]
    LiveEntity liveEntity;

    void FixedUpdate()
    {
        //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚Å‚Ì‚İ•\ï¿½ï¿½
        playPartCanvas.enabled = liveEntity.IsLive() && !liveEntity.GetGoaled();
        //ï¿½ï¿½ï¿½ñ‚¾ï¿½ï¿½Ì‚İ•\ï¿½ï¿½
        gameOverCanvas.enabled = liveEntity.IsDestructed();
        //ï¿½Sï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚İ•\ï¿½ï¿½
        goalCanvas.enabled = liveEntity.GetGoaled();

        Player player = null;

        if (liveEntity.GetCassette())
        {
            player = liveEntity.GetCassette().GetComponent<Player>();
        }
        if (player)
        {
            //EMPTYï¿½\ï¿½ï¿½ï¿½ÌˆÊ’uï¿½Æ‘å‚«ï¿½ï¿½ï¿½Aï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½^ï¿½Cï¿½~ï¿½ï¿½ï¿½Oï¿½ğ§Œï¿½
            RectTransform emptyRect =
                    emptyImage.gameObject.GetComponent<RectTransform>();
            emptyRect.anchoredPosition = currentCharaIconPos;
            emptyRect.localScale = new Vector3(1, 1, 1) * currentCharaIconSize;

            emptyImage.enabled = player.GetAttackReactionFrame() > 0
                && player.GetWeapons().Length <= 0;

            //ï¿½Aï¿½Cï¿½Rï¿½ï¿½ï¿½ÌŒï¿½ï¿½É‚ï¿½ï¿½é•ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ÌˆÊ’uï¿½Æ‘å‚«ï¿½ï¿½ï¿½ğ’²ï¿½
            for (int i = 0; i < Player.maxTeamNum; i++)
            {
                Image currentTray = charaImageTrays[i];
                RectTransform currentTrayRect =
                    currentTray.gameObject.GetComponent<RectTransform>();

                Vector2 currentPosition = currentCharaIconPos;
                Vector3 currentScale = new Vector3(1, 1, 1);
                if (i == 0)
                {
                    currentScale *= currentCharaIconSize;
                }
                else
                {
                    currentPosition -= new Vector2(0,
                        (currentCharaIconSize + (subCharaIconSize) * (i - 1))
                        * imgEXRate + (tabSize) * i);
                    currentScale *= subCharaIconSize;
                }
                currentTrayRect.anchoredPosition = currentPosition;
                currentTrayRect.localScale = currentScale;
            }

            //ï¿½Aï¿½Cï¿½Rï¿½ï¿½ï¿½ÌˆÊ’uï¿½Æ‘å‚«ï¿½ï¿½ï¿½ğ’²ï¿½
            for (int i = 0; i < Player.maxTeamNum; i++)
            {
                int currentIndex = Mathf.RoundToInt(
                    Mathf.Repeat(i - player.GetCurrentCharaIndex(),
                    Mathf.Max(player.GetWeapons().Length, 1)));

                Image currentIcon = charaImages[i];
                RectTransform currentTrayRect =
                    currentIcon.gameObject.GetComponent<RectTransform>();

                Vector2 currentPosition = currentCharaIconPos;
                Vector3 currentScale = new Vector3(1, 1, 1);
                if (currentIndex == 0)
                {
                    currentScale *= currentCharaIconSize;
                }
                else
                {
                    currentPosition -= new Vector2(0,
                        (currentCharaIconSize + (subCharaIconSize) * (currentIndex - 1))
                        * imgEXRate + (tabSize) * currentIndex);
                    currentScale *= subCharaIconSize;
                }
                currentTrayRect.anchoredPosition =
                    Vector2.Lerp(currentTrayRect.anchoredPosition, currentPosition,
                    iconSlideIntensity);
                currentTrayRect.localScale =
                    Vector3.Lerp(currentTrayRect.localScale, currentScale,
                    iconSlideIntensity);

                if (i < player.GetWeapons().Length)
                {
                    currentIcon.sprite = player.GetWeapons()[i].GetIconGraph();
                }
                else
                {
                    currentIcon.sprite = null;
                    currentTrayRect.localScale = Vector3.zero;
                }
            }
        }

        //ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Å‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½Î•ï¿½ï¿½ï¿½ï¿½Jï¿½Eï¿½ï¿½ï¿½gï¿½ï¿½ï¿½\ï¿½ï¿½
        reviveImage.gameObject.SetActive(liveEntity.GetReviveCount() > 0);
        //ï¿½ï¿½ï¿½ï¿½ï¿½Jï¿½Eï¿½ï¿½ï¿½gï¿½É•ï¿½ï¿½ï¿½ï¿½ñ”‚ï¿½\ï¿½ï¿½
        reviveCount.text = liveEntity.GetReviveCount().ToString();

        //ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½gï¿½ÌƒLï¿½ï¿½ï¿½Jï¿½Eï¿½ï¿½ï¿½gï¿½ÉŒï¿½ï¿½jï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½
        resultKillCount.text = liveEntity.GetKillCount().ToString();
        //ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½gï¿½Ì•ï¿½ï¿½ï¿½ï¿½Jï¿½Eï¿½ï¿½ï¿½gï¿½É‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ñ”‚ï¿½\ï¿½ï¿½
        resultReviveCount.text = liveEntity.GetReviveCount().ToString();
    }
}
